url: "https://urisherman.github.io/" 
baseurl: "" 
title: "Uri Sherman | Homepage"
description: "Academic homepage of Uri Sherman | Computer Science PhD candidate at Tel Aviv University, working on machine learning, stochastic optimization, and reinforcement learning"
author:
  name: Uri Sherman
  url: https://urisherman.github.io/

plugins:
  - jekyll-seo-tag